export const phoneCodes = [
  { name: 'Israel', dial_code: '+972', code: 'IL', russianName: 'Израиль' },
  { name: 'Afghanistan', dial_code: '+93', code: 'AF', russianName: 'Афганистан' },
  { name: 'Aland Islands', dial_code: '+358', code: 'AX', russianName: 'Аландские острова' },
  { name: 'Albania', dial_code: '+355', code: 'AL', russianName: 'Албания' },
  { name: 'Algeria', dial_code: '+213', code: 'DZ', russianName: 'Алжир' },
  { name: 'AmericanSamoa', dial_code: '+1 684', code: 'AS', russianName: 'Американское Самоа' },
  { name: 'Andorra', dial_code: '+376', code: 'AD', russianName: 'Андорра' },
  { name: 'Angola', dial_code: '+244', code: 'AO', russianName: 'Ангола' },
  { name: 'Anguilla', dial_code: '+1 264', code: 'AI', russianName: 'Ангилья' },
  {
    name: 'AntiguaandBarbuda',
    dial_code: '+1 268',
    code: 'AG',
    russianName: 'Антигуа и Барбуда',
  },
  { name: 'Argentina', dial_code: '+54', code: 'AR', russianName: 'Аргентина' },
  { name: 'Armenia', dial_code: '+374', code: 'AM', russianName: 'Армения' },
  { name: 'Aruba', dial_code: '+297', code: 'AW', russianName: 'Аруба' },
  { name: 'Australia', dial_code: '+61', code: 'AU', russianName: 'Австралия' },
  { name: 'Austria', dial_code: '+43', code: 'AT', russianName: 'Австрия' },
  { name: 'Azerbaijan', dial_code: '+994', code: 'AZ', russianName: 'Азербайджан' },
  { name: 'Bahamas', dial_code: '+1 242', code: 'BS', russianName: 'Багамы' },
  { name: 'Bahrain', dial_code: '+973', code: 'BH', russianName: 'Бахрейн' },
  { name: 'Bangladesh', dial_code: '+880', code: 'BD', russianName: 'Бангладеш' },
  { name: 'Barbados', dial_code: '+1 246', code: 'BB', russianName: 'Барбадос' },
  { name: 'Belarus', dial_code: '+375', code: 'BY', russianName: 'Беларусь' },
  { name: 'Belgium', dial_code: '+32', code: 'BE', russianName: 'Бельгия' },
  { name: 'Belize', dial_code: '+501', code: 'BZ', russianName: 'Белиз' },
  { name: 'Benin', dial_code: '+229', code: 'BJ', russianName: 'Бенин' },
  { name: 'Bermuda', dial_code: '+1 441', code: 'BM', russianName: 'Бермуды' },
  { name: 'Bhutan', dial_code: '+975', code: 'BT', russianName: 'Бутан' },
  {
    name: 'BosniaandHerzegovina',
    dial_code: '+387',
    code: 'BA',
    russianName: 'Босния и Герцеговина',
  },
  { name: 'Botswana', dial_code: '+267', code: 'BW', russianName: 'Боцвана' },
  { name: 'Brazil', dial_code: '+55', code: 'BR', russianName: 'Бразилия' },
  {
    name: 'British Indian Ocean Territory',
    dial_code: '+246',
    code: 'IO',
    russianName: 'Британская территория в Индийском океане',
  },
  { name: 'Bulgaria', dial_code: '+359', code: 'BG', russianName: 'Болгария' },
  { name: 'Burkina Faso', dial_code: '+226', code: 'BF', russianName: 'Буркина-Фасо' },
  { name: 'Burundi', dial_code: '+257', code: 'BI', russianName: 'Бурунди' },
  { name: 'Cambodia', dial_code: '+855', code: 'KH', russianName: 'Камбоджа' },
  { name: 'Cameroon', dial_code: '+237', code: 'CM', russianName: 'Камерун' },
  { name: 'Canada', dial_code: '+1', code: 'CA', russianName: 'Канада' },
  { name: 'Cabo Verde', dial_code: '+238', code: 'CV', russianName: 'Кабо-Верде' },
  { name: 'Cayman Islands', dial_code: '+ 345', code: 'KY', russianName: 'Каймановы острова' },
  {
    name: 'CentralAfricanRepublic',
    dial_code: '+236',
    code: 'CF',
    russianName: 'Центральноафриканская Республика',
  },
  { name: 'Chad', dial_code: '+235', code: 'TD', russianName: 'Чад' },
  { name: 'Chile', dial_code: '+56', code: 'CL', russianName: 'Чили' },
  { name: 'China', dial_code: '+86', code: 'CN', russianName: 'Китай' },
  { name: 'Christmas Island', dial_code: '+61', code: 'CX', russianName: 'Остров Рождества' },
  { name: 'Colombia', dial_code: '+57', code: 'CO', russianName: 'Колумбия' },
  { name: 'Comoros', dial_code: '+269', code: 'KM', russianName: 'Коморы' },
  {
    name: 'DemocraticRepublicoftheCongo',
    dial_code: '+243',
    code: 'CD',
    russianName: 'ДР Конго',
  },
  { name: 'RepublicoftheCongo', dial_code: '+242', code: 'CG', russianName: 'Конго' },
  { name: 'Cook Islands', dial_code: '+682', code: 'CK', russianName: 'Острова Кука' },
  { name: 'Costa Rica', dial_code: '+506', code: 'CR', russianName: 'Коста-Рика' },
  { name: 'Croatia', dial_code: '+385', code: 'HR', russianName: 'Хорватия' },
  { name: 'Cuba', dial_code: '+53', code: 'CU', russianName: 'Куба' },
  { name: 'Cyprus', dial_code: '+537', code: 'CY', russianName: 'Кипр' },
  { name: 'Czechia', dial_code: '+420', code: 'CZ', russianName: 'Чехия' },
  { name: 'Denmark', dial_code: '+45', code: 'DK', russianName: 'Дания' },
  { name: 'Djibouti', dial_code: '+253', code: 'DJ', russianName: 'Джибути' },
  { name: 'Dominica', dial_code: '+1 767', code: 'DM', russianName: 'Доминика' },
  {
    name: 'Dominican Republic',
    dial_code: '+1 849',
    code: 'DO',
    russianName: 'Доминиканская Республика',
  },
  { name: 'Ecuador', dial_code: '+593', code: 'EC', russianName: 'Эквадор' },
  { name: 'Egypt', dial_code: '+20', code: 'EG', russianName: 'Египет' },
  { name: 'El Salvador', dial_code: '+503', code: 'SV', russianName: 'Сальвадор' },
  {
    name: 'Equatorial Guinea',
    dial_code: '+240',
    code: 'GQ',
    russianName: 'Экваториальная Гвинея',
  },
  { name: 'Eritrea', dial_code: '+291', code: 'ER', russianName: 'Эритрея' },
  { name: 'Estonia', dial_code: '+372', code: 'EE', russianName: 'Эстония' },
  { name: 'Ethiopia', dial_code: '+251', code: 'ET', russianName: 'Эфиопия' },
  { name: 'Faroe Islands', dial_code: '+298', code: 'FO', russianName: 'Фарерские острова' },
  { name: 'Fiji', dial_code: '+679', code: 'FJ', russianName: 'Фиджи' },
  { name: 'Finland', dial_code: '+358', code: 'FI', russianName: 'Финляндия' },
  { name: 'France', dial_code: '+33', code: 'FR', russianName: 'Франция' },
  { name: 'French Guiana', dial_code: '+594', code: 'GF', russianName: 'Французская Гвиана' },
  { name: 'Polynesia French', dial_code: '+689', code: 'PF', russianName: 'Французская Полинезия' },
  { name: 'Gabon', dial_code: '+241', code: 'GA', russianName: 'Габон' },
  { name: 'Gambia', dial_code: '+220', code: 'GM', russianName: 'Гамбия' },
  { name: 'Georgia', dial_code: '+995', code: 'GE', russianName: 'Грузия' },
  { name: 'Germany', dial_code: '+49', code: 'DE', russianName: 'Германия' },
  { name: 'Ghana', dial_code: '+233', code: 'GH', russianName: 'Гана' },
  { name: 'Gibraltar', dial_code: '+350', code: 'GI', russianName: 'Гибралтар' },
  { name: 'Greece', dial_code: '+30', code: 'GR', russianName: 'Греция' },
  { name: 'Greenland', dial_code: '+299', code: 'GL', russianName: 'Гренландия' },
  { name: 'Grenada', dial_code: '+1 473', code: 'GD', russianName: 'Гренада' },
  { name: 'Guadeloupe', dial_code: '+590', code: 'GP', russianName: 'Гваделупа' },
  { name: 'Guam', dial_code: '+1 671', code: 'GU', russianName: 'Гуам' },
  { name: 'Guatemala', dial_code: '+502', code: 'GT', russianName: 'Гватемала' },
  { name: 'Guinea', dial_code: '+224', code: 'GN', russianName: 'Гвинея' },
  { name: 'Guinea-Bissau', dial_code: '+245', code: 'GW', russianName: 'Гвинея-Бисау' },
  { name: 'Guyana', dial_code: '+595', code: 'GY', russianName: 'Гайана' },
  { name: 'Haiti', dial_code: '+509', code: 'HT', russianName: 'Гаити' },
  { name: 'Honduras', dial_code: '+504', code: 'HN', russianName: 'Гондурас' },
  { name: 'Hungary', dial_code: '+36', code: 'HU', russianName: 'Венгрия' },
  { name: 'Iceland', dial_code: '+354', code: 'IS', russianName: 'Исландия' },
  { name: 'India', dial_code: '+91', code: 'IN', russianName: 'Индия' },
  { name: 'Indonesia', dial_code: '+62', code: 'ID', russianName: 'Индонезия' },
  { name: 'Iraq', dial_code: '+964', code: 'IQ', russianName: 'Ирак' },
  { name: 'Ireland', dial_code: '+353', code: 'IE', russianName: 'Ирландия' },
  { name: 'Israel', dial_code: '+972', code: 'IL', russianName: 'Израиль' },
  { name: 'Italy', dial_code: '+39', code: 'IT', russianName: 'Италия' },
  { name: 'Jamaica', dial_code: '+1 876', code: 'JM', russianName: 'Ямайка' },
  { name: 'Japan', dial_code: '+81', code: 'JP', russianName: 'Япония' },
  { name: 'Jordan', dial_code: '+962', code: 'JO', russianName: 'Иордания' },
  { name: 'Kazakhstan', dial_code: '+7 7', code: 'KZ', russianName: 'Казахстан' },
  { name: 'Kenya', dial_code: '+254', code: 'KE', russianName: 'Кения' },
  { name: 'Kiribati', dial_code: '+686', code: 'KI', russianName: 'Кирибати' },
  { name: 'Kuwait', dial_code: '+965', code: 'KW', russianName: 'Кувейт' },
  { name: 'Kyrgyzstan', dial_code: '+996', code: 'KG', russianName: 'Киргизия' },
  { name: 'Latvia', dial_code: '+371', code: 'LV', russianName: 'Латвия' },
  { name: 'Lebanon', dial_code: '+961', code: 'LB', russianName: 'Ливан' },
  { name: 'Lesotho', dial_code: '+266', code: 'LS', russianName: 'Лесото' },
  { name: 'Liberia', dial_code: '+231', code: 'LR', russianName: 'Либерия' },
  { name: 'Liechtenstein', dial_code: '+423', code: 'LI', russianName: 'Лихтенштейн' },
  { name: 'Lithuania', dial_code: '+370', code: 'LT', russianName: 'Литва' },
  { name: 'Luxembourg', dial_code: '+352', code: 'LU', russianName: 'Люксембург' },
  { name: 'Madagascar', dial_code: '+261', code: 'MG', russianName: 'Мадагаскар' },
  { name: 'Malawi', dial_code: '+265', code: 'MW', russianName: 'Малави' },
  { name: 'Malaysia', dial_code: '+60', code: 'MY', russianName: 'Малайзия' },
  { name: 'Maldives', dial_code: '+960', code: 'MV', russianName: 'Мальдивы' },
  { name: 'Mali', dial_code: '+223', code: 'ML', russianName: 'Мали' },
  { name: 'Malta', dial_code: '+356', code: 'MT', russianName: 'Мальта' },
  { name: 'Marshall Islands', dial_code: '+692', code: 'MH', russianName: 'Маршаловы острова' },
  { name: 'Martinique', dial_code: '+596', code: 'MQ', russianName: 'Мартиника' },
  { name: 'Mauritania', dial_code: '+222', code: 'MR', russianName: 'Мавритания' },
  { name: 'Mauritius', dial_code: '+230', code: 'MU', russianName: 'Маврикий' },
  { name: 'Mayotte', dial_code: '+262', code: 'YT', russianName: 'Майотта' },
  { name: 'Mexico', dial_code: '+52', code: 'MX', russianName: 'Мексика' },
  { name: 'Monaco', dial_code: '+377', code: 'MC', russianName: 'Монако' },
  { name: 'Mongolia', dial_code: '+976', code: 'MN', russianName: 'Монголия' },
  { name: 'Montenegro', dial_code: '+382', code: 'ME', russianName: 'Черногория' },
  { name: 'Montserrat', dial_code: '+1664', code: 'MS', russianName: 'Монтсеррат' },
  { name: 'Morocco', dial_code: '+212', code: 'MA', russianName: 'Марокко' },
  { name: 'Myanmar', dial_code: '+95', code: 'MM', russianName: 'Мьянма (Бирма)' },
  { name: 'Namibia', dial_code: '+264', code: 'NA', russianName: 'Намибия' },
  { name: 'Nauru', dial_code: '+674', code: 'NR', russianName: 'Науру' },
  { name: 'Nepal', dial_code: '+977', code: 'NP', russianName: 'Непал' },
  { name: 'Netherlands', dial_code: '+31', code: 'NL', russianName: 'Нидерланды' },
  {
    name: 'NetherlandsAntillesCountry',
    dial_code: '+599',
    code: 'AN',
    russianName: 'Нидерландские Антильские острова',
  },
  { name: 'New Caledonia', dial_code: '+687', code: 'NC', russianName: 'Новая Каледония' },
  { name: 'New Zealand', dial_code: '+64', code: 'NZ', russianName: 'Новая Зеландия' },
  { name: 'Nicaragua', dial_code: '+505', code: 'NI', russianName: 'Никарагуа' },
  { name: 'Niger', dial_code: '+227', code: 'NE', russianName: 'Нигер' },
  { name: 'Nigeria', dial_code: '+234', code: 'NG', russianName: 'Нигерия' },
  { name: 'Niue', dial_code: '+683', code: 'NU', russianName: 'Ниуэ' },
  { name: 'Norfolk Island', dial_code: '+672', code: 'NF', russianName: 'Остров Норфолк' },
  {
    name: 'Northern Mariana Islands',
    dial_code: '+1 670',
    code: 'MP',
    russianName: 'Северные Марианские Острова',
  },
  { name: 'Norway', dial_code: '+47', code: 'NO', russianName: 'Норвегия' },
  { name: 'Oman', dial_code: '+968', code: 'OM', russianName: 'Оман' },
  { name: 'Pakistan', dial_code: '+92', code: 'PK', russianName: 'Пакистан' },
  { name: 'Palau', dial_code: '+680', code: 'PW', russianName: 'Палау' },
  { name: 'Panama', dial_code: '+507', code: 'PA', russianName: 'Панама' },
  { name: 'PapuaNewGuinea', dial_code: '+675', code: 'PG', russianName: 'Папуа-Новая Гвинея' },
  { name: 'Paraguay', dial_code: '+595', code: 'PY', russianName: 'Парагвай' },
  { name: 'Peru', dial_code: '+51', code: 'PE', russianName: 'Перу' },
  { name: 'Philippines', dial_code: '+63', code: 'PH', russianName: 'Филиппины' },
  { name: 'Poland', dial_code: '+48', code: 'PL', russianName: 'Польша' },
  { name: 'Portugal', dial_code: '+351', code: 'PT', russianName: 'Португалия' },
  { name: 'Puerto Rico', dial_code: '+1 939', code: 'PR', russianName: 'Пуэрто-Рико' },
  { name: 'Qatar', dial_code: '+974', code: 'QA', russianName: 'Катар' },
  { name: 'Romania', dial_code: '+40', code: 'RO', russianName: 'Румыния' },
  { name: 'Rwanda', dial_code: '+250', code: 'RW', russianName: 'Руанда' },
  { name: 'Samoa', dial_code: '+685', code: 'WS', russianName: 'Самоа' },
  { name: 'San Marino', dial_code: '+378', code: 'SM', russianName: 'Сан-Марино' },
  { name: 'Saudi Arabia', dial_code: '+966', code: 'SA', russianName: 'Саудовская Аравия' },
  { name: 'Senegal', dial_code: '+221', code: 'SN', russianName: 'Сенегал' },
  { name: 'Serbia', dial_code: '+381', code: 'RS', russianName: 'Сербия' },
  { name: 'Seychelles', dial_code: '+248', code: 'SC', russianName: 'Сейшелы' },
  { name: 'Sierra Leone', dial_code: '+232', code: 'SL', russianName: 'Сьерра-Леоне' },
  { name: 'Singapore', dial_code: '+65', code: 'SG', russianName: 'Сингапур' },
  { name: 'Slovakia', dial_code: '+421', code: 'SK', russianName: 'Словакия' },
  { name: 'Slovenia', dial_code: '+386', code: 'SI', russianName: 'Словения' },
  { name: 'Solomon Islands', dial_code: '+677', code: 'SB', russianName: 'Соломоновы острова' },
  { name: 'South Africa', dial_code: '+27', code: 'ZA', russianName: 'ЮАР' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    dial_code: '+500',
    code: 'GS',
    russianName: 'Южная Георгия и Южные Сандвичевы острова',
  },
  { name: 'Spain', dial_code: '+34', code: 'ES', russianName: 'Испания' },
  { name: 'Sri Lanka', dial_code: '+94', code: 'LK', russianName: 'Шри-Ланка' },
  { name: 'Sudan', dial_code: '+249', code: 'SD', russianName: 'Судан' },
  { name: 'Suriname', dial_code: '+597', code: 'SR', russianName: 'Суринам' },
  { name: 'Swaziland', dial_code: '+268', code: 'SZ', russianName: 'Эсватини' },
  { name: 'Sweden', dial_code: '+46', code: 'SE', russianName: 'Швеция' },
  { name: 'Switzerland', dial_code: '+41', code: 'CH', russianName: 'Швейцария' },
  { name: 'Tajikistan', dial_code: '+992', code: 'TJ', russianName: 'Таджикистан' },
  { name: 'Thailand', dial_code: '+66', code: 'TH', russianName: 'Таиланд' },
  { name: 'Togo', dial_code: '+228', code: 'TG', russianName: 'Того' },
  { name: 'Tokelau', dial_code: '+690', code: 'TK', russianName: 'Токелау' },
  { name: 'Tonga', dial_code: '+676', code: 'TO', russianName: 'Тонга' },
  {
    name: 'TrinidadandTobago',
    dial_code: '+1 868',
    code: 'TT',
    russianName: 'Тринидад и Тобаго',
  },
  { name: 'Tunisia', dial_code: '+216', code: 'TN', russianName: 'Тунис' },
  { name: 'Turkey', dial_code: '+90', code: 'TR', russianName: 'Турция' },
  { name: 'Turkmenistan', dial_code: '+993', code: 'TM', russianName: 'Туркменистан' },
  {
    name: 'TurksandCaicosIslands',
    dial_code: '+1 649',
    code: 'TC',
    russianName: 'Острова Теркс и Кайкос',
  },
  { name: 'Tuvalu', dial_code: '+688', code: 'TV', russianName: 'Тувалу' },
  { name: 'Uganda', dial_code: '+256', code: 'UG', russianName: 'Уганда' },
  { name: 'Ukraine', dial_code: '+380', code: 'UA', russianName: 'Украина' },
  {
    name: 'Arab Emirates',
    dial_code: '+971',
    code: 'AE',
    russianName: 'Объединенные Арабские Эмираты',
  },
  { name: 'Great Britain', dial_code: '+44', code: 'GB', russianName: 'Великобритания' },
  {
    name: 'UnitedStatesofAmerica',
    dial_code: '+1',
    code: 'US',
    russianName: 'Соединенные Штаты Америки',
  },
  { name: 'Uruguay', dial_code: '+598', code: 'UY', russianName: 'Уругвай' },
  { name: 'Uzbekistan', dial_code: '+998', code: 'UZ', russianName: 'Узбекистан' },
  { name: 'Vanuatu', dial_code: '+678', code: 'VU', russianName: 'Вануату' },
  {
    name: 'Wallis and Futuna',
    dial_code: '+681',
    code: 'WF',
    russianName: 'Острова Уоллис и Футуна',
  },
  { name: 'Yemen', dial_code: '+967', code: 'YE', russianName: 'Йемен' },
  { name: 'Zambia', dial_code: '+260', code: 'ZM', russianName: 'Замбия' },
  { name: 'Zimbabwe', dial_code: '+263', code: 'ZW', russianName: 'Зимбабве' },
  { name: 'Antarctica', dial_code: null, code: 'AQ', russianName: 'Антарктика' },
  { name: 'Bolivia', dial_code: '+591', code: 'BO', russianName: 'Боливия' },
  { name: 'Brunei', dial_code: '+673', code: 'BN', russianName: 'Бруней' },
  { name: 'Cocos Islands', dial_code: '+61', code: 'CC', russianName: 'Кокосовые острова' },
  {
    name: 'Democratic Republic of the Congo',
    dial_code: '+243',
    code: 'CD',
    russianName: 'ДР Конго',
  },
  { name: "Cote d'Ivoire", dial_code: '+225', code: 'CI', russianName: "Кот-д'Ивуар" },
  {
    name: 'Falkland Islands',
    dial_code: '+500',
    code: 'FK',
    russianName: 'Фолклендские острова',
  },
  { name: 'Guernsey', dial_code: '+44', code: 'GG', russianName: 'Гернси' },
  { name: 'Vatican', dial_code: '+379', code: 'VA', russianName: 'Ватикан' },
  { name: 'Hong Kong', dial_code: '+852', code: 'HK', russianName: 'Гонконг' },
  { name: 'Iran', dial_code: '+98', code: 'IR', russianName: 'Иран' },
  { name: 'IsleofMan', dial_code: '+44', code: 'IM', russianName: 'Остров Мэн' },
  { name: 'Jersey', dial_code: '+44', code: 'JE', russianName: 'Джерси' },
  {
    name: 'Korea North',
    dial_code: '+850',
    code: 'KP',
    russianName: 'Корейская Народно-Демократическая Республика',
  },
  { name: 'Korea South', dial_code: '+82', code: 'KR', russianName: 'Южная Корея' },
  { name: 'Laos', dial_code: '+856', code: 'LA', russianName: 'Лаос' },
  { name: 'Libya', dial_code: '+218', code: 'LY', russianName: 'Ливия' },
  { name: 'Macao', dial_code: '+853', code: 'MO', russianName: 'Макао' },
  { name: 'Macedonia', dial_code: '+389', code: 'MK', russianName: 'Македония' },
  {
    name: 'Micronesia',
    dial_code: '+691',
    code: 'FM',
    russianName: 'Федеративные Штаты Микронезии',
  },
  { name: 'Moldova', dial_code: '+373', code: 'MD', russianName: 'Молдавия' },
  { name: 'Mozambique', dial_code: '+258', code: 'MZ', russianName: 'Мозамбик' },
  { name: 'Pitcairn', dial_code: '+872', code: 'PN', russianName: 'Острова Питкэрн' },
  { name: 'Russia', dial_code: '+7', code: 'RU', russianName: 'Россия' },
  { name: 'Saint Barthelemy', dial_code: '+590', code: 'BL', russianName: 'Сен-Бартелеми' },
  { name: 'Saint Helena', dial_code: '+290', code: 'SH', russianName: 'Остров Святой Елены' },
  {
    name: 'SaintKittsandNevis',
    dial_code: '+1 869',
    code: 'KN',
    russianName: 'Сент-Китс и Невис',
  },
  { name: 'Saint Lucia', dial_code: '+1 758', code: 'LC', russianName: 'Сент-Люсия' },
  { name: 'Saint Martin', dial_code: '+590', code: 'MF', russianName: 'Сен-Мартен' },
  {
    name: 'Saint Pierre and Miquelon',
    dial_code: '+508',
    code: 'PM',
    russianName: 'Сен-Пьер и Микелон',
  },
  {
    name: 'SaintVincentandtheGrenadines',
    dial_code: '+1 784',
    code: 'VC',
    russianName: 'Сент-Винсент и Гренадины',
  },
  {
    name: 'SaoTomeandPrincipe',
    dial_code: '+239',
    code: 'ST',
    russianName: 'Сан-Томе и Принсипи',
  },
  { name: 'Somalia', dial_code: '+252', code: 'SO', russianName: 'Сомали' },
  { name: 'Svalbard and Jan Mayen', dial_code: '+47', code: 'SJ', russianName: 'Шпицберген' },
  { name: 'Syria', dial_code: '+963', code: 'SY', russianName: 'Сирия' },
  { name: 'Taiwan', dial_code: '+886', code: 'TW', russianName: 'Тайвань' },
  { name: 'Tanzania', dial_code: '+255', code: 'TZ', russianName: 'Танзания' },
  { name: 'Timor-Leste', dial_code: '+670', code: 'TL', russianName: 'Восточный Тимор' },
  { name: 'Venezuela', dial_code: '+58', code: 'VE', russianName: 'Венесуэла' },
  { name: 'Vietnam', dial_code: '+84', code: 'VN', russianName: 'Вьетнам' },
  {
    name: 'BritishVirginIslands',
    dial_code: '+1 284',
    code: 'VG',
    russianName: 'Британские Виргинские Острова',
  },
  {
    name: 'the United States Virgin Islands',
    dial_code: '+1 340',
    code: 'VI',
    russianName: 'Виргинские острова Соединенных Штатов',
  },
];
